// Auto-generated by @farming-labs/next — do not edit manually.

import docsConfig from "@/docs.config";
import type { GeneratedChangelogEntry } from "@farming-labs/next/changelog";
import ChangelogEntry1 from "../release-notes/2026-08-26/page.mdx";
import ChangelogEntry2 from "../release-notes/2026-08-18/page.mdx";
import ChangelogEntry3 from "../release-notes/2026-05-17/page.mdx";
import ChangelogEntry4 from "../release-notes/2026-05-06/page.mdx";
import ChangelogEntry5 from "../release-notes/2026-04-07/page.mdx";
import ChangelogEntry6 from "../release-notes/2026-04-05/page.mdx";
import ChangelogEntry7 from "../release-notes/2026-04-02/page.mdx";
import ChangelogEntry8 from "../release-notes/2026-03-29/page.mdx";
import ChangelogEntry9 from "../release-notes/2026-03-24/page.mdx";
import ChangelogEntry10 from "../release-notes/2026-03-23/page.mdx";
import ChangelogEntry11 from "../release-notes/2026-03-22/page.mdx";
import ChangelogEntry12 from "../release-notes/2026-03-19/page.mdx";
import ChangelogEntry13 from "../release-notes/2026-03-16/page.mdx";
import ChangelogEntry14 from "../release-notes/2026-03-14/page.mdx";
import ChangelogEntry15 from "../release-notes/2026-03-11/page.mdx";
import ChangelogEntry16 from "../release-notes/2026-03-10/page.mdx";
import {
  createNextChangelogIndexMetadata,
  createNextChangelogIndexPage,
} from "@farming-labs/next/changelog";

export const changelogEntries: GeneratedChangelogEntry[] = [
  {
    slug: "2026-08-26",
    date: "2026-08-26",
    url: "/docs/changelog/2026-08-26",
    sourcePath: "app/docs/release-notes/2026-08-26/page.mdx",
    Component: ChangelogEntry1,
    metadata: {
      title: "Convex support",
      description:
        "Blyp adds isolate-safe logging for Convex functions with shared configuration and action-only connector export.",
      authors: ["Blyp"],
      tags: ["core", "convex", "integration", "connectors"],
    },
  },
  {
    slug: "2026-08-18",
    date: "2026-08-18",
    url: "/docs/changelog/2026-08-18",
    sourcePath: "app/docs/release-notes/2026-08-18/page.mdx",
    Component: ChangelogEntry2,
    metadata: {
      title: "Farm.js support",
      description:
        "Blyp adds a complete Farm.js integration with request logging, trace propagation, lifecycle events, and privacy-safe browser telemetry.",
      authors: ["Blyp"],
      version: "v0.1.26",
      tags: ["core", "farmjs", "telemetry"],
      pinned: true,
    },
  },
  {
    slug: "2026-05-17",
    date: "2026-05-17",
    url: "/docs/changelog/2026-05-17",
    sourcePath: "app/docs/release-notes/2026-05-17/page.mdx",
    Component: ChangelogEntry3,
    metadata: {
      title: "Stable authentication integrations and MongoDB",
      description:
        "Clerk, Better Auth, WorkOS, HTTP forwarding, and MongoDB support reach the stable core release.",
      authors: ["Blyp"],
      version: "v0.1.25",
      tags: ["core", "authentication", "mongodb", "connectors"],
    },
  },
  {
    slug: "2026-05-06",
    date: "2026-05-06",
    url: "/docs/changelog/2026-05-06",
    sourcePath: "app/docs/release-notes/2026-05-06/page.mdx",
    Component: ChangelogEntry4,
    metadata: {
      title: "Authentication integration beta",
      description:
        "The beta cycle introduces HTTP forwarding and the first Clerk, Better Auth, and WorkOS logging integrations.",
      authors: ["Blyp"],
      version: "v0.1.25-beta",
      tags: ["core", "beta", "authentication", "connectors"],
    },
  },
  {
    slug: "2026-04-07",
    date: "2026-04-07",
    url: "/docs/changelog/2026-04-07",
    sourcePath: "app/docs/release-notes/2026-04-07/page.mdx",
    Component: ChangelogEntry5,
    metadata: {
      title: "Typed configuration and SolidStart",
      description: "Blyp adds typed config authoring and a first-class SolidStart integration.",
      authors: ["Blyp"],
      version: "v0.1.24",
      tags: ["core", "configuration", "solidstart"],
    },
  },
  {
    slug: "2026-04-05",
    date: "2026-04-05",
    url: "/docs/changelog/2026-04-05",
    sourcePath: "app/docs/release-notes/2026-04-05/page.mdx",
    Component: ChangelogEntry6,
    metadata: {
      title: "Better Agent tracing and reasoning capture",
      description:
        "Blyp traces multi-step Better Agent runs, tool usage, token consumption, and opt-in reasoning payloads.",
      authors: ["Blyp"],
      version: "v0.1.23",
      tags: ["core", "ai", "better-agent", "tracing"],
    },
  },
  {
    slug: "2026-04-02",
    date: "2026-04-02",
    url: "/docs/changelog/2026-04-02",
    sourcePath: "app/docs/release-notes/2026-04-02/page.mdx",
    Component: ChangelogEntry7,
    metadata: {
      title: "Studio dashboard and observability expansion",
      description:
        "Studio gains HTTP, database, payment, background-job, authentication, error-triage, and agent observability views.",
      authors: ["Blyp"],
      version: "CLI v0.1.54–v0.1.55",
      tags: ["cli", "studio", "observability"],
    },
  },
  {
    slug: "2026-03-29",
    date: "2026-03-29",
    url: "/docs/changelog/2026-03-29",
    sourcePath: "app/docs/release-notes/2026-03-29/page.mdx",
    Component: ChangelogEntry8,
    metadata: {
      title: "AI tracing, durable delivery, and redaction",
      description:
        "A major core release adds AI traces, end-to-end trace IDs, durable connector queues, dead letters, and automatic sensitive-data redaction.",
      authors: ["Blyp"],
      version: "v0.1.22",
      tags: ["core", "ai", "tracing", "connectors", "security"],
    },
  },
  {
    slug: "2026-03-24",
    date: "2026-03-24",
    url: "/docs/changelog/2026-03-24",
    sourcePath: "app/docs/release-notes/2026-03-24/page.mdx",
    Component: ChangelogEntry9,
    metadata: {
      title: "React Router, Astro, Nitro, and Nuxt adapters",
      description: "Blyp broadens its framework support with four request-aware server adapters.",
      authors: ["Blyp"],
      version: "v0.1.21",
      tags: ["core", "react-router", "astro", "nitro", "nuxt"],
    },
  },
  {
    slug: "2026-03-23",
    date: "2026-03-23",
    url: "/docs/changelog/2026-03-23",
    sourcePath: "app/docs/release-notes/2026-03-23/page.mdx",
    Component: ChangelogEntry10,
    metadata: {
      title: "Studio packaging and brand fixes",
      description:
        "CLI releases align Studio colors with Blyp and repair a packaged Babel module crash.",
      authors: ["Blyp"],
      version: "CLI v0.1.52–v0.1.53",
      tags: ["cli", "studio", "fix"],
    },
  },
  {
    slug: "2026-03-22",
    date: "2026-03-22",
    url: "/docs/changelog/2026-03-22",
    sourcePath: "app/docs/release-notes/2026-03-22/page.mdx",
    Component: ChangelogEntry11,
    metadata: {
      title: "Live GitHub-backed skill installation",
      description:
        "The CLI moves skill discovery and installation from bundled assets to the latest Blyphq/skills repository.",
      authors: ["Blyp"],
      version: "CLI v0.1.51",
      tags: ["cli", "skills"],
    },
  },
  {
    slug: "2026-03-19",
    date: "2026-03-19",
    url: "/docs/changelog/2026-03-19",
    sourcePath: "app/docs/release-notes/2026-03-19/page.mdx",
    Component: ChangelogEntry12,
    metadata: {
      title: "Database-backed Studio logs",
      description:
        "Studio can read database destinations directly and presents grouped trace payloads more clearly.",
      authors: ["Blyp"],
      version: "CLI v0.1.5",
      tags: ["cli", "studio", "database", "tracing"],
    },
  },
  {
    slug: "2026-03-16",
    date: "2026-03-16",
    url: "/docs/changelog/2026-03-16",
    sourcePath: "app/docs/release-notes/2026-03-16/page.mdx",
    Component: ChangelogEntry13,
    metadata: {
      title: "Scoped package, database commands, and CLI rename",
      description:
        "Four releases complete the @blyp/core rename, repair declarations, add database scaffolding, and rename the executable to blyp.",
      authors: ["Blyp"],
      version: "Core v0.1.04/v0.1.2 · CLI v0.1.3/v0.1.4",
      tags: ["core", "cli", "database", "packaging", "migration"],
    },
  },
  {
    slug: "2026-03-14",
    date: "2026-03-14",
    url: "/docs/changelog/2026-03-14",
    sourcePath: "app/docs/release-notes/2026-03-14/page.mdx",
    Component: ChangelogEntry14,
    metadata: {
      title: "Blyp CLI launch and packaged Studio fixes",
      description:
        "The CLI launches with Studio, health, and skill commands while core adds Better Stack and TypeScript fixes.",
      authors: ["Blyp"],
      version: "Core v0.1.03 · CLI v0.1.0–v0.1.2",
      tags: ["core", "cli", "studio", "better-stack", "fix"],
    },
  },
  {
    slug: "2026-03-11",
    date: "2026-03-11",
    url: "/docs/changelog/2026-03-11",
    sourcePath: "app/docs/release-notes/2026-03-11/page.mdx",
    Component: ChangelogEntry15,
    metadata: {
      title: "Expo delivery, structured logs, and first-party connectors",
      description:
        "Two core releases add queued client delivery, request-scoped structured logs, and PostHog, Sentry, and OTLP support.",
      authors: ["Blyp"],
      version: "Core v0.1.01–v0.1.02",
      tags: ["core", "expo", "structured-logs", "connectors"],
    },
  },
  {
    slug: "2026-03-10",
    date: "2026-03-10",
    url: "/docs/changelog/2026-03-10",
    sourcePath: "app/docs/release-notes/2026-03-10/page.mdx",
    Component: ChangelogEntry16,
    metadata: {
      title: "Initial Blyp release",
      description:
        "Blyp launches with standalone, browser, framework, structured, and file logging for TypeScript applications.",
      authors: ["Blyp"],
      version: "v0.1.0",
      tags: ["core", "initial-release"],
    },
  },
];

export const metadata = createNextChangelogIndexMetadata(docsConfig);

const ChangelogPage = createNextChangelogIndexPage(docsConfig, changelogEntries);

export default ChangelogPage;
